name: emptiable_list
description: Container for a list-displaying widget, that can display a placeholder-widget when the list is empty.
version: 1.0.1
homepage: https://github.com/gorolykmaxim/emptiable_list

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: